title: Frontend Docs
description: Collection of notes that I use while developing web applications (work in process)
theme: just-the-docs

url: https://kushajveersingh.com/frontend-docs/

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: '11.4.1'

color_scheme: dark
enable_copy_code_button: true

compress_html:
  ignore:
    envs: all

back_to_top: true
back_to_top_text: 'Back to top'
